services:
  node-backend:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: primeview-node:latest
    ports:
      - "8000:8000"
    env_file:
      - ./node/.env
    restart: unless-stopped
    volumes:
      - ./node:/app
  

  python-ml-service:
    build:
      context: ./python-ml
      dockerfile: Dockerfile
    image: primeview-python-ml:latest
    ports:
      - "5050:5000"
    env_file:
      - ./python-ml/.env
    environment:
      - BACKEND_URL=http://node-backend:8080
    volumes:
      - ./python-ml:/app
